import pandas as pd
import os
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# Download the VADER dictionary (only needs to run once)
nltk.download('vader_lexicon', quiet=True)

# 0. load data
file_name = input("Enter the exact name of the cleaned CSV file to process: ")

if not os.path.exists(file_name):
    print(f"Error: Could not find '{file_name}'.")
    exit()

print("Loading data...")
df = pd.read_csv(file_name)


# 1. Create Table A: Product Dimension (dim_products)
print("Building Product Dimension Table...")
# Select only product-level columns
dim_products = df[['product_id', 'product_name', 'category', 'discounted_price', 
                   'actual_price', 'discount_percentage', 'rating', 'rating_count']].copy()

# Remove duplicates to ensure strictly 1 row per product
dim_products = dim_products.drop_duplicates(subset=['product_id'])

# Split the pipe-separated category string and keep the main category
dim_products['main_category'] = dim_products['category'].astype(str).str.split('|').str[0]
dim_products = dim_products.drop(columns=['category']) # Drop the messy original column


# 2. Create Table B: Review Fact Table (fact_reviews)
print("Building Review Fact Table...")
# Select review-level columns plus the product_id (Foreign Key)
fact_reviews = df[['product_id', 'user_id', 'review_id', 'review_title', 'review_content']].copy()

# The dataset contains comma-separated lists in these columns. 
# We need to split them into actual Python lists.
cols_to_split = ['user_id', 'review_id', 'review_title', 'review_content']

for col in cols_to_split:
    fact_reviews[col] = fact_reviews[col].astype(str).str.split(',')

# SAFETY CHECK: review_content might naturally contain commas (e.g., "Good product, works well"), 
# standard splitting might create uneven lists. force all lists to match the length of 'review_id' 
# to prevent the database from crashing during the 'explode' phase.
def align_lists(row):
    target_len = len(row['review_id'])
    for col in cols_to_split:
        if len(row[col]) < target_len:
            row[col] = row[col] + [''] * (target_len - len(row[col])) # Pad with blanks
        elif len(row[col]) > target_len:
            row[col] = row[col][:target_len] # Truncate extra
    return row

fact_reviews = fact_reviews.apply(align_lists, axis=1)

# explode lists
fact_reviews = fact_reviews.explode(cols_to_split)

# Clean up any empty/blank reviews generated by the explosion
fact_reviews = fact_reviews[fact_reviews['review_id'] != '']


# 3. sentiment analysis
print("Running NLP Sentiment Analysis on Reviews (This may take a moment)...")
sia = SentimentIntensityAnalyzer()

def calculate_sentiment(text):
    if pd.isna(text) or text == '':
        return 0.0
    # VADER returns a 'compound' score between -1 (Very Negative) and +1 (Very Positive)
    return sia.polarity_scores(str(text))['compound']

fact_reviews['sentiment_score'] = fact_reviews['review_content'].apply(calculate_sentiment)


# 4. export
print("Exporting Relational Tables...")
# Get the base name (e.g., 'amazon' from 'amazon_cleaned.csv')
base_name = file_name.replace('_cleaned.csv', '').replace('.csv', '')

products_filename = f"{base_name}_dim_products.csv"
reviews_filename = f"{base_name}_fact_reviews.csv"

dim_products.to_csv(products_filename, index=False)
fact_reviews.to_csv(reviews_filename, index=False)

print(f"1. Created Product Table: '{products_filename}' ({len(dim_products)} unique products)")
print(f"2. Created Review Table: '{reviews_filename}' ({len(fact_reviews)} individual reviews)")
print("These files can now be analyzed with SQL")